baseURL = "https://example.com/"
title = "Open Source in Business Guide"

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"

[params]
  BookSection = "*"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1
    languageName = "English"
  [languages.zh-tw]
    contentDir = "content/zh-tw"
    weight = 2
    languageName = "台灣正體中文"
    languageCode = "zh-TW"
