# defines a GitHub Action named "Build PDF" that is triggered on both pushes and pull requests 
# to the main branch. The on section specifies the event types that will trigger the workflow.
name: Build PDF
on:
  push:
    branches:x
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    # build will run on a ubuntu vm
    runs-on: ubuntu-latest
    # wihtin steps section. checks out the repository code using the actions/checkout action
    # & uses pandoc to build pdf file from markdown files contained in chapter folder
    # output will be stored wihtin docs folder as output.pdf
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install pandoc
      run: sudo apt-get update && sudo apt-get install pandoc
    - name: Build PDF
      run: |
        pandoc -N -s --template=template.latex -o output.pdf chapters/*.md
      working-directory: ./docs
    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: book-pdf
        path: docs/output.pdf
